name: build-and-upload-pages-dist

on:
    push:
        branches: [master]

permissions:
    contents: read

jobs:
    build-upload:
        runs-on: ubuntu-latest
        environment: build-upload
        steps:
            - uses: actions/checkout@v4

            - run: |
                  env
                  pwd

                  echo -e "dark495.cn" > CNAME
                  echo "url: \"https://dark495.cn\"" >> _config.yml
                  echo "baseurl: \"/\"" >> _config.yml
                  cat ./CNAME
                  cat ./_config.yml
                  ls -la

            - uses: actions/jekyll-build-pages@v1
              with:
                  source: ./
                  destination: ./_site
              env:
                  JEKYLL_ENV: production
                  PAGES_REPO_NWO: ""
                  PAGES_ENV: "" # 禁止GitHub Pages强制替换
                  PAGES_URL: "" # 彻底清空
                  JEKYLL_ENV_URL: "https://dark495.cn/" # 设置为国内镜像站地址，避免生成的站点内链接指向github.io

            - name: Pack
              run: |
                  cd _site
                  zip -r ../site.zip .

            - name: Upload (POST multipart)
              env:
                  UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
                  UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
              run: |
                  curl -sS -f -X POST "$UPLOAD_URL" \
                    -H "Authorization: Bearer $UPLOAD_TOKEN" \
                    -F "file=@site.zip" \
                    -o /dev/stdout
